name: my_wellness
description: Private preventive-health companion for My Wellness members.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  get_it: ^7.6.0
  injectable: ^2.1.2
  shared_preferences: ^2.2.3
  firebase_messaging: ^16.7.0
  firebase_database: ^12.6.0
  firebase_core: ^4.4.0
  flutter_animate: ^4.5.2
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - env/
