name: Deploy Documentation

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "pubspec.yaml" 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.5"
          channel: "stable"
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Code Generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Generate API Docs
        run: dart doc .

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/api

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4